name: Run Automation Bot

on:
  schedule:
    - cron: "0 10 * * *"  # Runs every day at 10:00 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow from the Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust Python version if needed

    - name: Install dependencies
      run: |
        sudo apt-get install -y chromium-chromedriver
        pip install selenium requests

    - name: Run the bot
      run: |
        python bot.py
